kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: cni-plugin-builder
  namespace: kube-system
  labels:
    k8s-app: cni-plugin-builder
spec:
  selector:
    matchLabels:
      k8s-app: cni-plugin-builder
  template:
    metadata:
      labels:
        k8s-app: cni-plugin-builder
        run-once-daemonset: cni-plugin-builder
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: |
          [
            {
              "key": "dedicated",
              "value": "master",
              "effect": "NoSchedule"
            },
            {
              "key": "CriticalAddonsOnly",
              "operator": "Exists"
            }
          ]
    spec:
      hostNetwork: true
      hostPID: true
      containers:
        - name: cni-plugin-builder
          image: jsteeleir/cni-plugin-builder
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /opt/cni/bin
              name: cni-bin-dir
      volumes:
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
